version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    env_file: 
      - ./.env
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge
